### ISSUE TITLE
TakePicture() doesn't save anything on the USB key.

### ISSUE THREAD

**Issue by maxence-charriere** [ARDrone2Windows/SDK#13]
Hello, I used the TakePicture() method on Windows Phone but nothing is saved on the USB key. In the other side, the video recording works perfectly.

Does somebody met this issue ?

(Even on the sample, the feature doesn't works).

**Comment by hoenic07** [comment]
Pictures are saved on the drone and can be accessed via FTP. I don't know if you can change it to save them on the USB stick per default...

**Comment by maxence-charriere** [comment]
Hi hoenic, thank you for the answer. I inserted the Video module into the WP client but a connection to the FTP throw an exception.
Doest I have to do something special ?

Do you have a code sample of a simple picture recuperation ?
