### ISSUE TITLE
Can't get the video stream on the sample WP8 application

### ISSUE THREAD

**Issue by AndrewSpec** [ARDrone2Windows/SDK#5]
I have only a black screen, no video is transmitted from the drone.

**Comment by AndrewSpec** [comment]
ok, got it. the WP8 sample is incomplete and that's the only problem. I've fixed it.

**Comment by TheRealDuckboy** [comment]
Glad you got it going. Can you give us an idea of what you had to do to make it work?

**Comment by AndrewSpec** [comment]
Sure.

On the FlyPage.xaml.cs you can find this code:
mediaElem.SetSource(new ARDroneStreamSource("192.168.1.1"));

but that code is in a unused method so finally the stream don't work. I've add that to the OnLoaded event and works fine. 

But still can't record that video to my usb...
