### ISSUE TITLE
Animation commands not working

### ISSUE THREAD

**Issue by kelman** [ARDrone2Windows/SDK#8]
Hi, 

I am trying the SDK and when using the W8 client and it seems that the animation command is ignored by the drone. Is there any specific task that I have to do before sending the command?

**Comment by Ruslan-B** [comment]
No you don't need to send anything in advance. 
Could you please check drone firmware version and post it with exact command being sent  (you could find it in the debug  output window).

**Comment by garolion** [comment]
Issue solved in the last update.
Flip animations need to be associated with a 6000 duration value.
